In [1]:
# import libraries for logistic regression on iris dataset
# install matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets


In [23]:
dataset = datasets.load_digits()
x = dataset.data
y = dataset.target

In [24]:
dataset.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
type(x)

numpy.ndarray

In [26]:
print(x)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [27]:
print(y)

[0 1 2 ... 8 9 8]


In [28]:
x[0:5, :]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

In [29]:
y[0:5, ]

array([0, 1, 2, 3, 4])

In [30]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [31]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [32]:
x.shape

(1797, 64)

In [33]:
y.shape

(1797,)

# Dataset Preparation

In [34]:
#Spliting the dataset to train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=7)

In [35]:
X_train.shape

(1257, 64)

In [36]:
y_train.shape

(1257,)

In [37]:
X_test.shape

(540, 64)

# Training the Model

In [40]:
#Finally, training the model
from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression(random_state=7)
classifier = LogisticRegression(random_state=0, max_iter=10000).fit(x, y)

classifier.fit(X_train,y_train)

LogisticRegression(max_iter=10000, random_state=0)

# Prediction

In [41]:
# prediction for model
y_pred = classifier.predict(X_test)

In [42]:
print(y_pred)

[6 0 5 3 2 9 0 4 1 0 1 8 2 5 2 5 1 8 5 1 0 2 0 4 5 3 3 0 0 4 1 4 4 4 6 1 4
 0 6 6 0 9 3 6 6 2 0 1 9 6 2 8 5 9 0 2 0 8 4 6 8 5 8 7 8 7 7 4 1 4 5 5 4 6
 2 0 1 3 7 5 8 2 4 4 2 5 1 9 3 7 6 3 3 5 6 2 1 0 1 9 4 1 9 5 1 6 9 0 3 7 6
 9 3 8 0 1 3 8 8 6 3 7 3 9 0 3 0 9 1 1 2 2 3 6 9 4 0 5 4 2 9 1 0 2 5 0 2 2
 7 4 8 9 8 2 6 0 4 4 5 5 0 2 4 6 2 2 3 7 2 9 0 3 5 9 1 6 8 7 5 3 0 4 2 1 3
 3 6 0 2 8 4 1 4 7 5 7 6 6 8 1 0 6 8 7 1 1 9 7 5 5 3 6 8 1 2 0 7 5 3 0 8 2
 0 4 0 9 4 8 4 7 9 7 3 6 2 8 1 5 9 2 9 9 8 2 1 6 7 5 7 5 7 8 5 5 7 4 3 7 7
 8 2 8 9 5 3 2 8 0 4 2 1 0 8 4 9 7 1 4 7 7 1 8 3 8 4 3 5 9 4 4 8 1 8 7 2 3
 1 1 1 0 2 8 0 7 4 0 1 0 2 3 7 9 8 5 8 2 2 6 5 0 5 9 8 9 0 0 9 7 4 1 2 6 7
 3 7 4 0 2 1 7 2 5 7 2 3 5 7 1 4 1 3 3 8 8 1 0 1 9 3 0 2 2 2 4 7 6 6 9 1 5
 9 9 2 9 0 7 0 9 6 8 5 7 3 0 5 0 7 1 0 7 9 8 9 6 4 8 8 4 4 3 3 9 9 6 1 3 8
 4 4 9 6 1 8 3 2 5 5 8 5 5 6 3 6 0 8 7 6 3 7 5 2 9 5 7 0 4 2 9 3 2 9 9 5 6
 0 5 4 4 4 0 5 5 6 3 6 4 7 2 8 6 6 9 8 0 0 0 4 3 4 3 9 7 1 7 8 1 9 9 7 4 3
 8 5 8 7 9 2 4 3 2 1 6 8 

In [43]:
print(y_test)

[6 0 5 9 2 9 0 4 1 0 1 8 2 5 2 8 1 8 9 1 0 2 0 4 5 3 3 0 0 4 1 4 4 4 6 1 4
 0 6 6 0 9 3 6 6 2 0 1 9 6 2 8 9 9 0 2 0 8 4 6 8 5 8 7 8 7 7 4 1 4 5 5 4 6
 2 0 1 3 7 5 8 2 4 4 2 5 1 9 3 7 6 3 3 5 6 2 1 0 1 9 4 1 1 3 1 6 9 0 3 7 6
 9 3 8 0 8 3 8 8 6 3 7 3 9 0 3 0 9 8 1 2 2 3 6 9 4 0 5 4 2 9 1 0 2 5 0 2 2
 7 4 6 9 8 2 6 0 4 4 8 5 0 2 4 6 8 2 3 7 2 9 0 3 5 9 1 6 8 7 5 3 0 4 2 1 3
 3 6 0 2 8 4 1 4 7 5 7 6 6 8 1 0 6 8 7 1 1 9 8 5 5 3 6 8 1 2 0 7 5 3 0 8 2
 0 4 0 9 4 8 4 7 9 7 3 6 2 5 1 5 9 2 9 9 8 2 1 6 7 1 7 5 7 8 9 5 7 4 3 7 8
 8 2 8 9 5 3 2 8 0 4 2 1 0 8 4 1 7 1 4 7 7 1 8 3 8 4 3 5 9 4 4 8 1 8 7 2 3
 1 1 1 0 2 8 0 7 4 0 1 0 2 3 7 9 8 5 8 2 2 6 5 0 8 9 8 9 0 0 9 7 4 1 2 6 7
 3 7 4 0 2 1 7 2 5 7 2 3 5 7 1 4 1 3 3 8 8 1 0 1 9 3 0 2 2 2 4 7 6 6 9 1 5
 9 9 2 9 0 7 0 9 6 1 5 7 3 0 5 0 7 1 0 7 9 8 9 6 4 8 8 4 4 3 3 9 9 6 1 3 8
 4 4 1 6 1 8 3 2 3 5 8 5 5 6 3 6 0 8 7 6 3 7 5 2 9 5 7 0 4 2 9 3 2 9 9 5 6
 0 5 4 4 4 0 5 5 6 3 6 4 4 2 8 6 6 9 8 0 0 0 4 3 4 3 9 7 1 7 8 1 9 9 7 4 3
 8 5 8 7 9 2 4 3 2 1 6 8 

# Model Evaluation

In [44]:
# Let's test the performance of our model - confusion Matrix 62
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

# Performance measure - Accuracy
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, y_pred))

[[61  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  1  0  0  1  3]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  1 49  0  2  0  0  0  0]
 [ 0  0  0  0 57  0  0  1  0  0]
 [ 0  0  0  0  0 47  0  0  1  0]
 [ 0  0  0  0  0  0 47  0  1  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  2  1  0  0  3  0  2 54  0]
 [ 0  0  0  1  0  3  0  0  0 50]]
Accuracy :  0.9574074074074074
